server {
    listen 80;
    server_name 13.250.62.106 _;

    location / {
        proxy_pass         http://app1-static:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    location /app {
        alias  /var/www/html;
        index  index.php;

        location ~ \.php$ {
            fastcgi_split_path_info ^/app(/.+\.php)(.*)$;
            fastcgi_pass            app2-php:9000;
            fastcgi_index           index.php;
            fastcgi_param           SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
            fastcgi_param           SCRIPT_NAME     $fastcgi_script_name;
            include                 fastcgi_params;
        }

        try_files $uri $uri/ /app/index.php$is_args$args;
    }
}
