name: CI/CD — UAS Cloud Computing II

on:
  push:
    branches: [main]

jobs:

  changes:
    name: "Detect Changed Paths"
    runs-on: ubuntu-latest
    outputs:
      app1: ${{ steps.filter.outputs.app1 }}
      app2: ${{ steps.filter.outputs.app2 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            app1:
              - 'app1-static/**'
            app2:
              - 'app2-php/**'

  build-app1:
    name: "App1 — Build & Push Static Web"
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.app1 == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./app1-static
          push: true
          tags: muhamadmahbub383/uas_2388010014:app1-latest

  build-app2:
    name: "App2 — Build & Push PHP App"
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.app2 == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./app2-php
          push: true
          tags: muhamadmahbub383/uas_2388010014:app2-latest

  deploy:
    name: "Deploy — AWS EC2 Zero-Touch"
    runs-on: ubuntu-latest
    needs: [build-app1, build-app2]
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      (needs.build-app1.result == 'success' || needs.build-app2.result == 'success')
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/scp-action@v0.1.7
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          source:   "docker-compose.yml,nginx/,app2-php/init.sql"
          target:   "/home/${{ secrets.EC2_USER }}/uas-project"
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.EC2_USER }}/uas-project
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
            echo "✅ Deploy selesai — $(date '+%Y-%m-%d %H:%M:%S')"
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
